---
# tasks file for tailscale

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ tailscale_dependencies }}"

- name: Add the Tailscale repository (yum/dnf)
  ansible.builtin.yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    baseurl: "{{ tailscale_repo_baseurl }}"
    gpgcheck: no
    repo_gpgcheck: yes
    gpgkey: "{{ tailscale_repo_gpgkey }}"
  when:
    - ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "dnf"

- name: Configure apt repository
  when:
    - ansible_pkg_mgr == "apt"
  block:
    - name: Add apt key
      ansible.builtin.apt_key:
        url: "{{ tailscale_apt_key_url }}"
        keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Apt apt repository
      ansible.builtin.apt_repository:
        repo: "{{ tailscale_apt_repo }}"
        filename: tailscale

- name: Add tailscale repository (zypper)
  community.general.zypper_repository:
    repo: "{{ tailscale_repo_baseurl }}"
  when:
    - ansible_pkg_mgr == "zypper"

- name: Install tailscale
  ansible.builtin.package:
    name: tailscale

- name: Enable and start the server
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Modify settings for the exit node
  when:
    - tailscale_exit_node
  block:
    - name: Install sysctl
      ansible.builtin.package:
        name: "{{ tailscale_sysclt_packages }}"

    - name: Check for /etc/sysctl.d
      ansible.builtin.stat:
        path: /etc/sysctl.d
      register: tailscale_sysctl_d

    - name: Allow forwarding in sysctl.d
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_file: "{{ tailscale_sysctl_file }}"
      loop:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding

    - name: Gather the package facts
      ansible.builtin.package_facts:

    - name: Allow masquarading
      ansible.posix.firewalld:
        masquerade: yes
        state: enabled
        permanent: true
      when:
        - "'firewalld' in ansible_facts.packages"

- name: Check tailscale status
  ansible.builtin.command:
    cmd: tailscale status
  register: tailscale_status
  changed_when: no
  failed_when: no

- name: Run tailscale up
  block:
    - name: Run tailscale up with authkey
    - name: Run tailscale up with advertised routes
      ansible.builtin.command:
        cmd: "{{ tailscale_up_command }} --advertise-routes={{ tailscale_advertise_routes | join(',') }}"
      changed_when: yes
      when:
        - tailscale_advertise_routes is defined
        - tailscale_advertise_routes != []
      notify:
        - Add firewall forward
