---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-tailscale
      # When setting the `tailscale_authkey`, a node can join automatically.
      # In case the `tailscale_authkey` is unset, registration of the node is manual.
      # tailscale_authkey: "tskey-auth-KEY_IDENTITY-KEY_SERET_KEY_SERET_KEY_SERET_KE"
      #
      # You can request the node to publish itself as an exit node.
      # tailscale_exit_node: yes
      #
      # You can advertise certain routes to the Tailscale network.
      # tailscale_advertise_routes:
      #   - 10.0.0.0/24
      #   - 10.0.1.0/24
      tailscale_authkey: "tskey-auth-k3rpMK7CNTRL-HgzyuzFU86QRU5EgvLok6QReBaNXtwGG"
      tailscale_exit_node: yes
