---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-tailscale
      # tailscale_authkey: "tskey-auth-KEY_IDENTITY-KEY_SERET_KEY_SERET_KEY_SERET_KE"
      tailscale_exit_node: yes
      tailscale_advertise_routes:
        - 10.0.0.0/24
        - 10.0.1.0/24
